baseURL = "https://edd255.github.io/"
languageCode = "en-us"
title = "edd255"
theme = ["github.com/adityatelange/hugo-PaperMod"]

[params]
math = true
title = "edd255"
ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = false
ShowBreadCrumbs = false
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true

[params.homeInfoParams]
Title = "Hi there 👋"
Content = "I play CTFs sometimes."

[[params.socialIcons]]
name = "rss"
url = "/index.xml"

[[params.socialIcons]]
name = "github"
url = "https://github.com/edd255"

[markup]
[markup.goldmark]
[markup.goldmark.extensions]
[markup.goldmark.extensions.passthrough]
enable = true

[markup.goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['\(', '\)']]

[outputs]
home = ["html", "rss", "json"]

[caches.images]
dir = ":cacheDir/images"
