baseURL = "https://edd255.github.io/"
languageCode = "en-us"
title = "edd255"
theme = ["github.com/mrmierzejewski/hugo-theme-console"]

[caches]
[caches.images]
dir = ':cacheDir/images'

[params]
math = true

[markup]
[markup.goldmark]
[markup.goldmark.extensions]
[markup.goldmark.extensions.passthrough]
enable = true

[markup.goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['\(', '\)']]
