baseURL = "https://edd255.github.io/"
languageCode = "en-us"
title = "edd255"
theme = ["github.com/adityatelange/hugo-PaperMod"]

[caches]
[caches.images]
dir = ':cacheDir/images'

[params]
math = true
title = "edd255"
description = "I play CTFs sometimes."

[params.homeInfoParams]
Title = "Hi there 👋"
Content = "I play CTFs sometimes."

[markup]
[markup.goldmark]
[markup.goldmark.extensions]
[markup.goldmark.extensions.passthrough]
enable = true

[markup.goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['\(', '\)']]
